### ISSUE TITLE
Hurley is dead project now

### ISSUE THREAD

**Issue by vanitu** [edwardsamuel/google-maps-services-ruby#3]
https://github.com/lostisland/hurley/issues/43

**Comment by edwardsamuel** [comment]
Yes, Hurley is a dead project. This issue has been reported in #1. Hurley is not going to be yanked as the author stated in your link.

Actually, in develop branch, I already replaced Hurley with [HTTPClient](https://github.com/nahi/httpclient). But, I have no free time for this project in the past few months.

**Comment by vanitu** [comment]
Ok. closing this issue than.

**Comment by spickermann** [comment]
Since Ruby 2.7.1 Hurley pollutes the log files by raising deprecation warnings. I wonder how are your plans to replace Hurley with HTTPClient?

**Comment by Pritilender** [comment]
And since Ruby 3 Hurley breaks this gem by raising `ArgumentError: tried to create Proc object without a block`. It would be great if you could release the develop branch. Or if there is some more work needed regarding usage of HTTPClient, I'd be willing to help.
